# tasks file
---
- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - locales
    - locales-include-variables

- name: Include Debian/Ubuntu tasks
  ansible.builtin.include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include RedHat/Rocky tasks
  ansible.builtin.include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'
